services:
  # db:
  #   container_name: next14-boilerplate-db
  #   image: postgres
  #   restart: no
  #   environment:
  #     POSTGRES_USER: db
  #     POSTGRES_PASSWORD: db
  #     POSTGRES_DB: next14-boilerplate-db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  redis:
    container_name: next14-boilerplate-redis
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db-data:
